name: pro_connect_tz
description: ProConnectTexnikTopshirig'i

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

  # Carousel_Slider package
  carousel_slider: ^4.2.1

  # Equatable package
  equatable: ^2.0.5

  # Flutter_bloc package
  flutter_bloc: ^8.1.3

  #bloc
  bloc: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: sfprodisplay
      fonts:
        - asset: assets/fonts/sf_pro_display/font_sfprodisplay.OTF
          weight: 400
